# flake8: noqa
# Name and Description each symbol
import pandas as pd
from sqlalchemy import create_engine

stocks_business_types = {
    "ADVANC": "Operate telecommunication business including mobile network service, fixed broadband service, and digital services.",
    "AOT": "AOT is the operator of airport business in Thailand, the core tasks of which are airport management and development of country's 6 international airports, namely Suvarnabhumi, Don Mueang, Chiang Mai, Mae Fah Luang-Chiang Rai, Phuket and Hat Yai. All 6 serve both domestic and international flights with Suvarnabhumi designated as the country's main airport.",
    "AWC": "AWC is a holding company that also run various companies that operate, manage hospitality and commercial properties. We are supported by TCC Group in our hospitality, retail and commercial businesses consisting of Retail & Wholesale and Office Building in Thailand.",
    "BANPU": "Integrated Energy Solutions Company by creating growth throughout its 3 core groups of businesses, which are Energy Resources (coal and gas including related operations such as marketing, trading, logistics, fuel procurement, and transmission), Energy Generation (conventional and renewable power plants), and Energy Technology (total solar energy solutions, energy storage system and energy technology system) By incorporating both conventional and unconventional or renewable businesses within the Groups portfolio structure, Banpu then has a stronger integration across its core business units resulting in more effective resources management and a balanced business expansion which offers sustainable energy solutions for consumers, communities, society and the environment.",
    "BBL": "The Bank provides full commercial banking services in corporate SME including retail customer with nationwide network. The Bank's overseas branch network spans economies zone.",
    "BDMS": "The Bank provides full commercial banking services in corporate SME including retail customer with nationwide network. The Bank's overseas branch network spans economies zone.",
    "BEM": "Construction and operation of the Expressway and Operation Management of Mass Rapid Transit System Business, including related business.",
    "BGRIM": "A holding company holding shares in other companies of which the core business is generation and sale of electricity and steam and related business in Thailand and other countries.",
    "BH": "The Company operates a private hospital, Bumrungrad International hospital in Bangkok, which serves local and international patients. The Company provides complete healthcare services for outpatients and inpatients and invests in related healthcare services businesses.",
    "BTS": "A multi-industry conglomerate utilising data and partnerships to amplify value from its proprietary transport and media network through our 3 core businesses, MOVE, MIX and MATCH.",
    "CBG": "Engage as a holding company to hold and invest in companies that operate vertically integrated business activities of manufacturing, marketing, selling and managing distribution of energy drinks and other beverages",
    "CENTEL": "The Company is the operator and manager of many hotels in Thailand and international countries. The Company's current portfolio includes the owned established Centara Grand, Centara, Centra, Cosi brands and manage hotels. The Company is also the pioneer of Western QSR brands in Thailand, currently the operator under its owned brand, The Terrace, Aroi Dee, Suki House, Soft Air, Kowlune and franchised brands of Mister Donut, KFC, Auntie Anne's, Pepper Lunch, Cold Stone Creamery, Chabuton, Yoshinoya, Ootoya, Tenya and Katsuya. Total QSR outlets are around in Thailand.",
    "COM7": "COM7 distributes IT products such as laptops, desktop computers, mobile phones, tablets, related accessories and product repair services. COM7 is the largest IT chain store in term of branches. COM7 distributes IT products via its own branches which are retail stores in leading department stores, shopping malls, and hypermarkets covering Bangkok and upcountry provinces.",
    "CPALL": 'The Company operates the convenience store business under the 7-Eleven trademark and franchises to other retailers in the territory of Thailand and has invested in supporting businesses such as manufacturing facility of food & bakery products, bill payment services and so on. In addition, the Company has invested in the operations of membership based Cash & Carry trade centers under the name "Makro".',
    "CPF": "The Company engages in agro-industrial and food conglomerate with 3 product catagories : 1) Feed business involving in production and sale of anminal feed, 2) Farm-Processing business involving in breeding, farming and basic meat processing, 3) Food business involving in production of semi-cooked and cooked meet as well as ready-meal products including food retail and food outlets.",
    "CPN": "Develop and invest in retail property for rent comprising large-scale shopping complexes and other related and supportive businesses, such as office buildings, hotels, residential development and food court. In addition, the Company invests in CPN Commercial Growth Leasehold Property Fund (CPNCG) and CPN Retail Growth Leasehold REIT (CPNREIT), and is the property manager and REIT manager.",
    "CRC": "Operate as multi-format,multi-category retailing platform in Thailand, Italy, and Vietnam. Also a pioneer in omni-channel retailing in Thailand, complementing retail store network and merchandise offerings with leading positions among store-based retailers in online traffic.",
    "DELTA": "The Company's businesses are mainly involved in power management solutions and manufacture of electronic components i.e. DC fan, electromagnetic interference filter (EMI) and solenoid. Its operation has covered regions such as Asia, Europe and South America.",
    "EA": "The Company currently operates 4 major businesses, which can be attributed to 1.) Biodiesel Business 2.) Renewable Power Plant Business- Wind Power Plant- Solar Power Plant 3.) Electric Vehicle and Energy Storage System- Battery development, manufacturing, and distribution business- Electric charging station service business (For electric vehicles) - Electric Vehicle Business4.) Other Businesses -Battery Electric Vehicle and Electronic Products Testing Center- Research and Development",
    "EGCO": "The Company operates as a holding company with its main business in 1) Operating power plants and supply electricity through independent power producer (IPP) and small power producers (SPP), 2) Providing operation, maintenance, engineering and construction services to power plants, petrochemical plants, oil refineries and other industries",
    "GLOBAL": "The Company operates its businesses under concept of modern trade from construction material to home improvement supplies. It is a one-stop shopping home center, which offers construction material, home decorative products, tools and equipment used in construction, home improvement, and household and gardening decoration in modern trade warehouse style. Additionally, the Company implemented a drive-through system to increase ease of access and convenience for customer.",
    "GPSC": "Company operates as a power, steam, and utilities producer and distributor. In addition, the company invests in other companies that generate and distribute power, steam, utilities, and New S-Curve business: batteries and smart energy, including related businesses, both domestic and overseas.",
    "GULF": "Holding company that invests in a portfolio of conventional and renewable power generation and distribution businesses, as well as natural gas supply and distribution, infrastructure development projects, and other related businesses.",
    "HMPRO": "Retailer of products and provider of services relating to construction, extension, refurbishment, and improvement of home and residence",
    "INTUCH": "INTOUCH is a holding company with investments in the telecom, media and technology (TMT) sector, including digital businesses.",
    "IVL": "Indorama Ventures Public Company Limited, a holding company conducting its business through investment in subsidiaries and affiliates engaged in the manufacture of integrated petrochemical products both domestic and overseas. These companies manufacture and distribute Ethylene Oxide and Ethylene Glycol (EO&EG), Purified Terephthalic Acid (PTA), Polyethylene Terephthalate (PET), Polyester Fiber and Yarn and Wool products.",
    "KBANK": "KASIKORNBANK PCL (KBank) conducts commercial banking, securities and other related businesses per the Financial Institutions Business Act, Securities and Exchange Act and other regulations. KBank primarily provides financial services via an extensive branch network nationwide. As of 31 December 2022, KBank service coverage remains available in all locales and is adequate to meet our customers requirements. Currently, KBank has 824 branches and 10,953 self-service channels to help customers conduct transactions on their own. In addition, the Banks international network now includes 16 establishments in 8 countries, with operations and services centralized at the Head Office.",
    "KCE": "The core business of the Company is the production and distribution of painted circuit boards (PCBs) manufactured from an epoxy glass copper lead laminate. The Company is now able to produce high quality and complex multilayer boards. The PCB is the foundation component of computers, automotive industry, telecommunication devices and most electronic equipment.",
    "KTB": "The Company is a large commercial bank in Thailand conducting its business through a nationwide branch network and in certain major centers of the world.",
    "KTC": "Operates a credit card business as its main business, including credit card related business, merchant acquiring business, payment service, as well as a personal loan business which includes personal loan business under supervision and auto title loan. The Company also established the subsidiaries and added a full range of financial products covering provincial retail lending business, occupational retail lending business, e-money business, hire purchase and leasing business, as well as holding business.",
    "LH": "The Company focuses on the development of quality residential projects in the category of detached houses, townhouses and residential condominiums for sale to target customers according to the needs of customers at different price levels by focusing on project development in Bangkok and boundaries and projects in the large provinces such as Chiang Mai, Chiang Rai, Nakorn Ratchasima, Khon Kaen, Maha Sarakham, Udon Thani, Prachuap Khiri Khan, Ayutthaya, and Phuket.",
    "MINT": "Food and Beverages, Hotel and Mixed-use including Residential Development, Point-Based Vacation Club and Plaza and Entertainment Business, together with Retail Trading.",
    "MTC": "The Company provides vehicle title loan and personal loan to individuals.",
    "OR": "The company operates an integrated oil and non-oil retailing platform both in Thailand and abroad, including the sales and distribution of petroleum products and other products in retail and commercial marketing, coffee shops, other food and beverage outlets, convenience stores and space management offerings.",
    "OSP": "Produces, markets and distributes consumer products with a focuson core products such as beverages, personal care, and other businesses,including healthcare, confectionery, providing product and packagingmanufacturing (OEM) and vending machines",
    "PTT": "The Company's operated businesses consist of natural gas, gas transmission, international trading, new business and infrastructure business; the rest are invested through subsidiaries joint arrangements and associates, and PTT Group, namely exploration and production, liquefied natural gas, petrochemical and refining, oil and retail, power and utilities, coal and service businesses.",
    "PTTEP": "The principal business operations of the the Group are exploration and production of petroleum in Thailand and overseas, foreign gas pipeline transportation, and investment in projects strategically connected to the energy business",
    "PTTGC": "PTT Global Chemical Public Company Limited was founded on 19th October 2011 through the amalgamation of PTT Chemical Public Company Limited and PTT Aromatics and Refining Public Company Limited to be the chemical flagship of PTT Group.",
    "RATCH": "The Company is operated as a holding company, RATCH seeks to equity invest in core companies, subsidiaries, and/ or joint ventures, subject to its shareholding proportion. Its investment is mainly focused on fossil fuel power generation projects, renewable projects as well as businesses adjacent to electricity generation and energy both in Thailand and internationally. Its main incomes are in forms of dividend and profit sharing from invested companies.",
    "SAWAD": 'The Company provides loan services to retail customers under the brand "Srisawad Ngern Sod Tun Jai". Business operation of the Company can be classified into 5 main categories: 1) Secured loan against all types of used vehicle, home, and land 2) Unsecured personal loan 3) Asset management 4) Debt collection service 5) Consultancy service to implement and manage the credit-provision process.',
    "SCB": "SCBX was established to operate business as a holding company of the financial business group and holding shares in other companies for the purpose of having the control over these companies. The Company will determine the strategies for the Group, seek for investment opportunities, and allocate funds to invest in businesses that will continuously create sustainable growth and returns for the Group. In addition, the Company will also be responsible for policies and corporate governance, business operations, risk management, and business continuity management of companies in the financial business group. In this regard, SCBX's business scope will be in accordance with the regulations prescribed by the Bank of Thailand.",
    "SCC": "The Company operates as holding company engaging in the industrial supplies and construction industries. The Company operates 3 core businesses consists of investments in the Cement-Building Materials business, Chemicals business and Packaging business.",
    "SCGP": "The Company generates revenue from holding shares in other companies (Holding Company),operating core business as an integrated packaging solutions provider (The key subsidiary engagingin the core business is Siam Kraft Industry Co., Ltd.), which is organized into three main businesses:Integrated Packaging Business, Fibrous Business, and Recycling Business and Others.",
    "TISCO": 'The Company is holding company of TISCO Group which TISCO Bank is its core business. TISCO Bank engages in banking business with service areas including retail and SME lending, corporate lending, retail deposit, private banking, bancassurance, cash management and custodian services.',
    "TOP": 'Thaioil is Thailands largest refinery and supplier of petroleum products. Founded in 1961, Thaioil is one of the leading and efficient refineries in Asia Pacific with the current capacity of 275,000 barrels per day.Thaioil has expanded to other related business including petrochemicals-aromatics and olefin chain, lube base oil, power generation, LAB (an intermediate in the production of cleaning agents), solvents/chemicals. In addition, there are also ethanol and supporting businesses such as pipeline transportation, ethanol, recruitment services for Thaioil and Subsidiaries, as well as Treasury Center to enhance Thaioil and Subsidiaries capability of financial management.',
    "TRUE": 'Telecommunication service provider which provide digital services and digital convergence lifestyle covering cellular and wireless telecommunication, internet broadband, WiFi, TV, content and digital media platform.',
    'TTB': 'The Bank engages in universal banking business to serve corporate, SME, and retail customers. ING Bank B.V., a financial group in the Netherland, is its strategic partner and a major shareholder as well as Ministry of Finance.',
    'TU': 'The Company engages in the manufacture and export of frozen and canned seafood. Its comprehensive business is completed with snack foods such as canned food, frozen food and snacks of various types especially seafood. Also, its businesses include packaging and publishing business, domestic market business, animal feed and development of shrimp species for sale business and commercial shrimp hatchery and nursery.',
    'WHA': 'The Company is the leader of one-stop service which covers all of customer demands relating to logistics services of which classifies into 4 business hubs i.e. Logistics Hub, Industrial Development Hub, Utilities & Power Hub, and Digital Platform Hub. The Company sets a clear policy to sell its assets into Real-Estate Investment Trust (WHART, WHAIR and WHABT), as an additional source of fund for the continuing of the Company?s real estate development. In addition, the Company has been appointed to be the property manager for those real-estate investment trusts and the property funds. Furthermore, the Company has policy to invest in the real-estate business through investment in the real-estate investment trusts and/or the property funds to generate recurring income in the form of dividends.'
}

stocks_full_name = {
    'ADVANC': 'Advanced Info Service Public Company Limited',
    'AOT': 'Airports of Thailand Public Company Limited',
    'AWC': 'Asset World Corporation Public Company Limited',
    'BANPU': 'Banpu Public Company Limited',
    'BBL': 'Bangkok Bank Public Company Limited',
    'BDMS': 'Bangkok Dusit Medical Services Public Company Limited',
    'BEM': 'Bangkok Expressway and Metro Public Company Limited',
    'BGRIM': 'B.Grimm Power Public Company Limited',
    'BH': 'Bumrungrad Hospital Public Company Limited',
    'BTS': 'BTS Group Holdings Public Company Limited',
    'CBG': 'Carabao Group Public Company Limited',
    'CENTEL': 'Central Plaza Hotel Public Company Limited',
    'COM7': 'Com7 Public Company Limited',
    'CPALL': 'CP All Public Company Limited',
    'CPF': 'Charoen Pokphand Foods Public Company Limited',
    'CPN': 'Central Pattana Public Company Limited',
    'CRC': 'Central Retail Corporation Public Company Limited',
    'DELTA': 'Delta Electronics (Thailand) Public Company Limited',
    'EA': 'Energy Absolute Public Company Limited',
    'EGCO': 'Electricity Generating Public Company Limited',
    'GLOBAL': 'Siam Global House Public Company Limited',
    'GPSC': 'Global Power Synergy Public Company Limited',
    'GULF': 'Gulf Energy Development Public Company Limited',
    'HMPRO': 'Home Product Center Public Company Limited',
    'INTUCH': 'Intouch Holdings Public Company Limited',
    'IVL': 'Indorama Ventures Public Company Limited',
    'KBANK': 'Kasikornbank Public Company Limited',
    'KCE': 'KCE Electronics Public Company Limited',
    'KTB': 'Krung Thai Bank Public Company Limited',
    'KTC': 'Krungthai Card Public Company Limited',
    'LH': 'Land and Houses Public Company Limited',
    'MINT': 'Minor International Public Company Limited',
    'MTC': 'Muangthai Capital Publie Company Limited',
    'OR': 'PTT Oil And Retail Business Public Company Limited',
    'OSP': 'Osotspa Public Company Limited',
    'PTT': 'PTT Public Company Limited',
    'PTTEP': 'PTT Exploration and Production Public Company Limited',
    'PTTGC': 'PTT Global Chemical Public Company Limited',
    'RATCH': 'Ratch Group Public Company Limited',
    'SAWAD': 'Srisawad Corporation Public Company Limited',
    'SCB': 'SCBX Public Company Limited',
    'SCC': 'The Siam Cement Public Company Limited',
    'SCGP': 'SCG Packaging Public Company Limited',
    'TISCO': 'TISCO Financial Group Public Company Limited',
    'TOP': 'Thai Oil Public Company Limited',
    'TRUE': 'True Corporation Public Company Limited',
    'TTB': 'TMBThanachart Bank Public Company Limited',
    'TU': 'Thai Union Group Public Company Limited',
    'WHA': 'WHA Corporation Public Company Limited',
}

if __name__ == "__main__":
    engine = create_engine('sqlite:///./project.db', echo=False)

    df = pd.DataFrame(index=['full_name'], data=stocks_full_name)
    # df = df.reindex(sorted(df.columns), axis=1)
    _df = pd.DataFrame(index=['business_types'], data=stocks_business_types)
    # _df = _df.reindex(sorted(_df.columns), axis=1)
    df = pd.concat([df, _df], axis=0).reset_index()
    df.to_sql(name="specific_info", con=engine, if_exists="replace")
